# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/ruby_linear_regression/all/ruby_linear_regression.rbi
#
# ruby_linear_regression-0.1.5

class RubyLinearRegression
  def compute_cost(test_x = nil, test_y = nil); end
  def compute_gradient(parameter); end
  def initialize; end
  def lambda; end
  def load_training_data(x_data, y_data, normalize = nil); end
  def mu; end
  def normalize; end
  def normalize_data(x_data, mu = nil, sigma = nil); end
  def predict(data); end
  def sigma; end
  def theta; end
  def train_gradient_descent(alpha = nil, iterations = nil, verbose = nil); end
  def train_normal_equation(l = nil); end
  def x; end
  def y; end
end
